### ISSUE TITLE
AppEngine NotFound and silent error when initialising project location

### ISSUE THREAD

**Issue by thclark** [flamingo-run/gcp-pilot#34]
In the GCP Pilot API base class [here](https://github.com/flamingo-run/gcp-pilot/blob/730a2538451392e5e631e1453ea81a11f71100b0/gcp_pilot/base.py#L69), the location is set, in the following priority:
- explicitly provided value
- default from a setting
- project default determined using AppEngine [here](https://github.com/flamingo-run/gcp-pilot/blob/730a2538451392e5e631e1453ea81a11f71100b0/gcp_pilot/base.py#L209)

I think historically, GCP projects had a default AppEngine resource always available. Nowadays they don't (I think this only happened in the last year or so).

This code handles a `NotFound` exception silently, catching it to return `None`. This however, causes many problems later on, a variety of NotFound or PermissionDenied errors when trying to create or access resources at `project/<project-id>/location/None/rest-of-it`

I think that it's an antipattern allow the location value to be `None` at the end of the base __init__, we should know at the point of failure there's been an error rather than much later. How about somehting like:
```py

class GoogleCloudPilotAPI(abc.ABC):
    def __init__(
        #stuff
    ):
        #stuff
        self.location = self._set_location(location=location)
        if location is None:
            raise NoLocationError("Couldn't set location from either explicit argument, GCP_LOCATION environment variable or from AppEngine")

```
?

**Comment by joaodaher** [comment]
You're totally correct regarding the location requirement.
Since there's APIs that require and APIs that don't, we should only fail when the `location` is used (or maybe earlier if not set but required?).

If you have an approach in mind, please create a PR. :)
